{% set name = "rq_scheduler" %}
{% set version = "0.13.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/rq-scheduler-{{ version }}.tar.gz
  sha256: 89d6a18f215536362b22c0548db7dbb8678bc520c18dc18a82fd0bb2b91695ce

build:
  entry_points:
    - rqscheduler = rq_scheduler.scripts.rqscheduler:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - pip
  run:
    - python >={{ python_min }}
    - crontab >=0.23.0
    - rq >=0.13
    - python-dateutil
    - freezegun

test:
  imports:
    - rq_scheduler
  commands:
    - pip check
    - rqscheduler --help
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/rq/rq-scheduler
  summary: Provides job scheduling capabilities to RQ (Redis Queue)
  license: MIT
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - sanurielf
